config/routes.rb
Rails.application.routes.draw do

  get '/codecheck/:code' => 'inicial#codecheck', :as => 'code_checker'

  get 'expiredcode' => 'inicial#codeused', :as => 'codeused'

  post 'check_your_mail' => 'inicial#check_you_mail', :as => 'check_your_mail'

  get 'thankyou' => 'inicial#thankyou', :as => 'thankyou'

  post 'payformessage' => 'inicial#pay_for_message', :as => 'pay_for_message'

  get 'delivered/' => 'inicial#deliver_boss_message', :as => 'deliver_boss_message'

  get 'cancel/:token' => 'inicial#cancel_mail_send', :as => 'cancel_boss_message'

  get 'error' => 'inicial#error', :as => 'error'

  get 'about' => 'inicial#about', :as => 'about'
  get 'terms_and_conditions' => 'inicial#terms', :as => 'terms'

  root 'inicial#index'

end

app/models/mail_code.rb
class MailCode < ActiveRecord::Base
    before_create :generate_token

    has_one :message


    def generate_token
        self.code = loop do
            random_token = SecureRandom.urlsafe_base64(nil, false)
            break random_token unless MailCode.exists?(code: random_token)
        end

        self.sec_code = loop do
            random_token = SecureRandom.urlsafe_base64(nil, false)
            break random_token unless MailCode.exists?(sec_code: random_token)
        end
    end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :mail_code
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/inicial_controller.rb
class InicialController < ApplicationController
  rescue_from Paypal::Exception::APIError, with: :paypal_api_error

  def index

  end

  def check_you_mail
      @email = params[:youremail]
      @domain = params[:youremail].partition('@').last
      @mailcode = MailCode.create(domain: @domain, fromail: @email)

      SendMail.sendcode(@email,@mailcode).deliver_now

  end

  def codecheck
      @domain = MailCode.find_by_code(params[:code])

      if @domain
          if @domain.used
              redirect_to codeused_path
          else
              @message = @domain.build_message
          end
      else
          redirect_to codeused_path
      end

  end

  def codeused

  end

  def thankyou

  end

  def pay_for_message
      @domain = MailCode.find_by_code(params[:code])

      if @domain.used
          redirect_to codeused_path
      else
          @message = @domain.build_message(to: "#{params[:message][:to]}@#{@domain.domain}", message: params[:message][:message]).save

          if Rails.env.production?
              require 'geoip'
              currency = GeoIP.new("#{Rails.root}/db/GeoIP.dat").country(request.remote_ip).country_name == "Brazil" ? :BRL : :USD

              paypal_options = {
                  no_shipping: true, # if you want to disable shipping information
                  allow_note: false, # if you want to disable notes
                  pay_on_paypal: true # if you don't plan on showing your own confirmation step
              }

              request = Paypal::Express::Request.new(
                  :username   => 'contact_api2.bossmesser.com',
                  :password   => 'SR2HER6C7Z53VJ2L',
                  :signature  => 'ALqNpbZpva18Rgg6Pv5ifOTOyWHdAnSs1SOhpi5P0r7EXgv6-CxvYbxM'
              )
              payment_request = Paypal::Payment::Request.new(
                  :currency_code => currency,   # if nil, PayPal use USD as default
                  :description   => "Send a Anonym Feedback to your Boss",    # item description
                  :quantity      => 1,      # item quantity
                  :amount        => 1.00,   # item value
                  :custom_fields => {
                      CARTBORDERCOLOR: "FFFF66",
                      LOGOIMG: "http://www.bossmesser.com/bossmesser-mail.png"
                  }
              )

              response = request.setup(
                  payment_request,
                  deliver_boss_message_url,
                  error_url,
                  paypal_options  # Optional
              )

              @domain.update_attribute(:token, response.token)

              redirect_to response.redirect_uri

          else
              redirect_to deliver_boss_message_path(:token => @domain.code)
          end


      end
  end

  def error

  end

  def deliver_boss_message

      if Rails.env.production?
          require 'geoip'
          currency = GeoIP.new("#{Rails.root}/db/GeoIP.dat").country(request.remote_ip).country_name == "Brazil" ? :BRL : :USD

          request = Paypal::Express::Request.new(
              :username   => 'contact_api2.bossmesser.com',
              :password   => 'SR2HER6C7Z53VJ2L',
              :signature  => 'ALqNpbZpva18Rgg6Pv5ifOTOyWHdAnSs1SOhpi5P0r7EXgv6-CxvYbxM'
          )

          token = params[:token]
          payer_id = params[:PayerID]
          payment_request = Paypal::Payment::Request.new(
              :currency_code => currency,   # if nil, PayPal use USD as default
              :description   => "Send a Anonym Feedback to your Boss",    # item description
              :quantity      => 1,      # item quantity
              :amount        => 1.00,   # item value
              :custom_fields => {
                  CARTBORDERCOLOR: "FFFF66",
                  LOGOIMG: "http://www.bossmesser.com/bossmesser-mail.png"
              }
          )

          @domain = MailCode.find_by_token(token)

          response = request.checkout!(
              token,
              payer_id,
              payment_request
          )
      else
          @domain = MailCode.find_by_code(params[:token])
      end

      SendMail.send_cancel_token(@domain.fromail, @domain.code).deliver_now

      SendMail.delay(run_at: 2.days.from_now, token: @domain.code).sendbossmessage(@domain.message)

      SendMail.delay(run_at: 2.days.from_now).sendbosscopymessage(@domain.fromail, @domain.message)

      @domain.update_attribute(:used, true)

      redirect_to thankyou_path
  end

  def cancel_mail_send
      token = params[:token]

      @email = Delayed::Job.find_by_token(token)

      if @email
          @email.destroy
          @message = "The email to your boss will not be delivered. Glad to see that you are in peace!"
      else
          @message = "This token is invalid and this message is not on our queue. If there are more than 2 days, it's already delivered. If not, good right?"

      end

  end

  def about

  end

  def terms

  end

  def paypal_api_error(e)
      errors = e.response.details.collect(&:long_message).join('<br />')
      p errors

      redirect_to error_path, flash[:errors] = errors
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicial_helper.rb
module InicialHelper
end

app/views/inicial/about.html.erb
<h2>Who are we?</h2>
<div class="row">
  <div class="col-xs-12">
    <h4>So... we are bossmesser, a tool that allows you to sent an constructive email to your boss, but... anonymously :)</h4>
    <p>And by constructive, we mean it. Trust us, nothing will help you more than a really constructive statement. Rage will always bring you results that you don't really want. Works better for you and your boss to manage your relation problems.</p>

    <p>If you are a Boss that had been messed, please, don't take it personal. Sometimes people just go mad. But, we hope you have received a nice feedback, if not, just ignore it, after all we all make mistakes right?</p>
    <p>And, huh, if you want you still can send us an email at contact@bossmesser.com and we can send you a nice leadership consultant that will improve your work and relations for good.</p>

  </div>
</div>

app/views/inicial/cancel_mail_send.html.erb
<h1><%= @message %></h1>

app/views/inicial/check_you_mail.html.erb
<h1>A message has been sent to your email address. In this message you'll need to click on the link that will allow you to send a message for an email address on this domain: <%= @domain %></h1>

app/views/inicial/codecheck.html.erb
<h3>you have confirmed your domain address and now, you are allowed to send a anonym message for any address on the domain: <%= @domain.domain %></h3>

<p>If you send suggestions and constructive material, you probably get better results than actually just messing with your boss. How about that?</p>

<div class="row show-grid">
  <div class="col-xs-4">
    <%= form_for @message, :url => pay_for_message_path do |f| %>
        <%= hidden_field_tag :code, @domain.code %>
        <div class="row">
          <%= f.text_field :to, :placeholder => 'ex: my_dear_boss', :class => 'mail_name text' %>@<%= @domain.domain %>
        </div>
        <div class="row">
          Message:
        </div>
        <div class="row">
          <%= f.text_area :message, :class => 'mail_message', :maxlength => "1000", :placeholder => "Hey, be polite. It works better then otherwise. Trust us."  %>
        </div>
        <div class="row">
          <%= f.button 'Send Anonym Message', :class => 'mail_button' %>
        </div>
    <% end %>
  </div>
  <div class="col-xs-8">
    <h3>Hey, listen up: We can EXCLUSIVELY send an anonymous email for you but we cannot PROTECT you from being found. This is because there are other ways from being discovered, and also the non-tech ways. Our Suggestion: BE POLITE AND CONSTRUCTIVE. It worth it.</h3>
    <h4>Bad words WILL BE SANITIZED.</h4>
    <strong>By Clicking on 'Send Anonym Message' to send this anonymous message, accept our terms and conditions and accept that your email contains no illegal,
      abusing, harrassing or likewise content. Also you declare yourself responsible for anything that is on its content.</strong>
    <p>After you send your message a link will be sent to YOUR email. It you change your mind, you have two days to cancel its submition by clicking on it. If you dont't, your message will be delivered automatically in 2 days.</p>

  </div>
</div>

app/views/inicial/codeused.html.erb
<h1>Sorry, this code is already used or invalid.</h1>

app/views/inicial/error.html.erb
<h1>An error has been ocurred on your payment</h1>

<% if flash[:errors] %>
    <h2><%= flash[:errors] %></h2>
<% end %>

app/views/inicial/index.html.erb
<div class="text-wrap">
  <strong class="title">Send a nice constructive email to your Boss... Anonymously... for 1$ :)</strong>
  <%= form_tag check_your_mail_path, :class => 'signup-form' do %>
      <fieldset>
        <div class="row">
          <%= email_field_tag :youremail, '' ,:required => true, :placeholder => 'Enter YOUR email address' %>
          <%= button_tag 'Send Confirmation' %>
        </div>
        <span class="info">Hey... be constructive, is not because you are anonymous that you need to be a prick. And... we WILL show your email if you <strong>violate our terms of use and the law ask us to do so</strong>. This is just an anonymous email tool, also there are a billion ways to be discovered, so... be nice! We assure you that the email will be sent from feedback@bossmesser.com, not that it will be impossible to track you.</span>
      </fieldset>
  <% end %>
</div>

app/views/inicial/thankyou.html.erb
<h1>Your message will be delivered to your boss in two days! We hope it was constructive. <strong>If you think better and decides to cancel the delivery, please click at the link that we just sent to your mail</strong>, but keep in mind there will be no refund.</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BossMesser</title>

  <link rel="icon" href="favicon.ico">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta property="og:title" content="BossMesser - Send a Anonymous and (please) Constructive feedback to your Boss."/>
  <meta property="og:site_name" content="BossMesser" />
  <meta property="og:image" content="http://www.bossmesser.com/bossmesser-mail.png"/>
  <meta property="og:url" content="http://www.bossmesser.com/"/>
  <meta property="og:type" content="webtool"/>
  <meta property="og:description" content="A service that allows you to send a constructive feedback for your boss. Hey, messer is just the name, be kind as you expect people will be with yourself."/>

  <meta name="description" content="A service that allows you to send a constructive feedback for your boss. Hey, messer is just the name, be kind as you expect people will be with yourself.">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="inner">
<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '532606873508588',
            xfbml      : true,
            version    : 'v2.2'
        });
    };

    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-59221485-1', 'auto');
    ga('send', 'pageview');

</script>
<div
class="fb-like"
data-share="true"
data-width="450"
data-show-faces="true">
</div>

<div id="wrapper">

  <header id="header">
    <div class="container">
      <div class="header-text">
        <div class="logo-holder">
          <a href="#"><%= image_tag 'bossmesser.png' %></a>
        </div>

        <%= yield %>

      </div>
    </div>
  </header>
  <footer id="footer">
    <nav class="footer-nav">
      <ul>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Terms & Conditions', terms_path %></li>
      </ul>
    </nav>
  </footer>
</div>

</body>

</html>

app/views/send_mail/send_cancel_token.html.erb
<table class="centered" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto">
  <tbody><tr>
    <td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #eded5f;width: 1px">​</td>
    <td style="padding: 0;vertical-align: top">
      <table class="one-col" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px;background-color: #ffffff;font-size: 14px">
        <tbody><tr>
          <td class="column" style="padding: 0;vertical-align: top;text-align: left">
            <div><div class="column-top" style="font-size: 32px;line-height: 32px">&nbsp;</div></div>
            <table class="contents" style="border-collapse: collapse;border-spacing: 0;width: 100%">
              <tbody><tr>
                <td class="padded" style="padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px">

                  <h1 style="Margin-top: 0;color: #565656;font-weight: 700;font-size: 36px;Margin-bottom: 18px;font-family: sans-serif;line-height: 42px">Here's your link to Cancel the Delivery</h1>
                  <p style="Margin-top: 0;color: #565656;font-family: Georgia,serif;font-size: 16px;line-height: 25px;Margin-bottom: 25px">With this link you can cancel the delivery of the anonymous e-mail to your boss Keep it.</p>
                  <p style="Margin-top: 0;color: #565656;font-family: Georgia,serif;font-size: 16px;line-height: 25px;Margin-bottom: 24px">By clicking on it before 2 days, you cancel permanently the delivery process. Click <strong style="font-weight: bold"><%= link_to 'Here', @url %></strong> to cancel the anonym email for your boss.</p>
                  <p style="Margin-top: 0;color: #565656;font-family: Georgia,serif;font-size: 16px;line-height: 25px;Margin-bottom: 25px">Ps: There will be no refund by doing this.</p>

                </td>
              </tr>
              </tbody></table>

            <div class="column-bottom" style="font-size: 8px;line-height: 8px">&nbsp;</div>
          </td>
        </tr>
        </tbody></table>
    </td>
    <td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #eded5f;width: 1px">​</td>
  </tr>
  </tbody>
</table>

app/views/send_mail/sendbosscopymessage.html.erb
<table class="centered" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto">
  <tbody><tr>
    <td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #eded5f;width: 1px">​</td>
    <td style="padding: 0;vertical-align: top">
      <table class="one-col" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px;background-color: #ffffff;font-size: 14px">
        <tbody><tr>
          <td class="column" style="padding: 0;vertical-align: top;text-align: left">
            <div><div class="column-top" style="font-size: 32px;line-height: 32px">&nbsp;</div></div>
            <table class="contents" style="border-collapse: collapse;border-spacing: 0;width: 100%">
              <tbody><tr>
                <td class="padded" style="padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px">

                  <h1 style="Margin-top: 0;color: #565656;font-weight: 700;font-size: 36px;Margin-bottom: 18px;font-family: sans-serif;line-height: 42px">You have received a feedback from your employee</h1>
                  <h3 style="Margin-top: 0;color: #565656;font-weight: 700;font-size: 36px;Margin-bottom: 18px;font-family: sans-serif;line-height: 42px">Don't Worry, it's just a copy.</h3>
                  <strong style="font-weight: bold">Beginning of the Message:</strong>
                  <p style="Margin-top: 0;color: #565656;font-family: Georgia,serif;font-size: 16px;line-height: 25px;Margin-bottom: 25px"><%= @message %></p>
                  <strong style="font-weight: bold">End of the Message:</strong>
                  <p style="Margin-top: 0;color: #565656;font-family: Georgia,serif;font-size: 16px;line-height: 25px;Margin-bottom: 24px">Hope it was constructive, and if it wasn't, dont bother yourself. Sometimes people just want to say stuff.</p>
                  <p style="Margin-top: 0;color: #565656;font-family: Georgia,serif;font-size: 16px;line-height: 25px;Margin-bottom: 24px">But if you tought that it was constructive and want to improve, how about a consulting process? Send an email to <a href="mailto:contact@bossmesser.com">contact@bossmesser.com</a> and we'l figure out how to help.</p>
                </td>
              </tr>
              </tbody></table>

            <div class="column-bottom" style="font-size: 8px;line-height: 8px">&nbsp;</div>
          </td>
        </tr>
        </tbody></table>
    </td>
    <td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #eded5f;width: 1px">​</td>
  </tr>
  </tbody>
</table>

app/views/send_mail/sendbossmessage.html.erb
<table class="centered" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto">
  <tbody><tr>
    <td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #eded5f;width: 1px">​</td>
    <td style="padding: 0;vertical-align: top">
      <table class="one-col" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px;background-color: #ffffff;font-size: 14px">
        <tbody><tr>
          <td class="column" style="padding: 0;vertical-align: top;text-align: left">
            <div><div class="column-top" style="font-size: 32px;line-height: 32px">&nbsp;</div></div>
            <table class="contents" style="border-collapse: collapse;border-spacing: 0;width: 100%">
              <tbody><tr>
                <td class="padded" style="padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px">

                  <h1 style="Margin-top: 0;color: #565656;font-weight: 700;font-size: 36px;Margin-bottom: 18px;font-family: sans-serif;line-height: 42px">You have received a feedback from your employee</h1>
                  <strong style="font-weight: bold">Beginning of the Message:</strong>
                  <p style="Margin-top: 0;color: #565656;font-family: Georgia,serif;font-size: 16px;line-height: 25px;Margin-bottom: 25px"><%= @message %></p>
                  <strong style="font-weight: bold">End of the Message:</strong>
                  <p style="Margin-top: 0;color: #565656;font-family: Georgia,serif;font-size: 16px;line-height: 25px;Margin-bottom: 24px">Hope it was constructive, and if it wasn't, dont bother yourself. Sometimes people just want to say stuff.</p>
                  <p style="Margin-top: 0;color: #565656;font-family: Georgia,serif;font-size: 16px;line-height: 25px;Margin-bottom: 24px">But if you tought that it was constructive and want to improve, how about a consulting process? Send an email to <a href="mailto:contact@bossmesser.com">contact@bossmesser.com</a> and we'l figure out how to help.</p>
                </td>
              </tr>
              </tbody></table>

            <div class="column-bottom" style="font-size: 8px;line-height: 8px">&nbsp;</div>
          </td>
        </tr>
        </tbody></table>
    </td>
    <td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #eded5f;width: 1px">​</td>
  </tr>
  </tbody>
</table>

app/views/send_mail/sendcode.html.erb
<table class="centered" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto">
  <tbody><tr>
    <td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #eded5f;width: 1px">​</td>
    <td style="padding: 0;vertical-align: top">
      <table class="one-col" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px;background-color: #ffffff;font-size: 14px">
        <tbody><tr>
          <td class="column" style="padding: 0;vertical-align: top;text-align: left">
            <div><div class="column-top" style="font-size: 32px;line-height: 32px">&nbsp;</div></div>
            <table class="contents" style="border-collapse: collapse;border-spacing: 0;width: 100%">
              <tbody><tr>
                <td class="padded" style="padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px">

                  <h1 style="Margin-top: 0;color: #565656;font-weight: 700;font-size: 36px;Margin-bottom: 18px;font-family: sans-serif;line-height: 42px">Here's your link to the Mailform</h1>
                  <p style="Margin-top: 0;color: #565656;font-family: Georgia,serif;font-size: 16px;line-height: 25px;Margin-bottom: 25px">Now that we can see that you actually are from this domain, you can click <%= link_to 'Here', @url %> to go our mail form and send you boss an anonym message.</p>
                  <p style="Margin-top: 0;color: #565656;font-family: Georgia,serif;font-size: 16px;line-height: 25px;Margin-bottom: 24px">Keep in mind our <a href="http://www.bossmesser.com/terms_and_conditions">Terms & Conditions</a> agreement and <strong style="font-weight: bold">be constructive.</strong> It's better for you and for your boss.</p>

                </td>
              </tr>
              </tbody></table>

            <div class="column-bottom" style="font-size: 8px;line-height: 8px">&nbsp;</div>
          </td>
        </tr>
        </tbody></table>
    </td>
    <td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #eded5f;width: 1px">​</td>
  </tr>
  </tbody>
</table>